AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "bin/**/*"
    - "spec/spec_helper.rb"

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Metrics/MethodLength:
  Max: 25

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"

Layout/LineLength:
  Max: 150
