name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec
      - name: Build gem
        run: gem build gh-health.gemspec
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gem-package
          path: "*.gem"

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: gem-package
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.gem"
          generate_release_notes: true
